package utils

enum class ErrorCode {
    OK,
    MISSING_STRING, MISSING_INTEGER, INVALID_INTEGER, MISSING_DOUBLE, INVALID_DOUBLE,
    INVALID_ARGUMENT_FORMAT, INVALID_ARGUMENT_NAME, UNEXPECTED_ARGUMENT
}